version: '3'
services:
  bookstdd:
    image: mysql:latest
    restart: always
    container_name: bookstdd
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: booktdd
      MYSQL_ROOT_PASSWORD: root
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    environment:
      - spring.profiles.active=test
    depends_on:
      - bookstdd
volumes:
  mysql:

